In [15]:
import pandas as pd

In [16]:
train = pd.read_csv('data/train.csv')
print(train.head(5))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [17]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [18]:
test = pd.read_csv('data/test.csv')
print(test.head(5))

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

#### Punto 2.
El dataset de Test no tiene la variable "survived" porque esta variable es de prediccion y no queremos que nuestro modelo aprenda de memoria al predecir

In [19]:
test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [20]:
data_dict = {
    "Variable": ["PassengerId", "Survived", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Ticket", "Fare", "Cabin", "Embarked"],
    "Descripción": [
        "Identificador único",
        "0 = No sobrevivió, 1 = Sobrevivió",
        "1 = 1ª Clase, 2 = 2ª Clase, 3 = 3ª Clase",
        "Nombre y título",
        "Género",
        "Edad en años",
        "Nº de hermanos/cónyuges a bordo",
        "Nº de padres/hijos a bordo",
        "Número del ticket",
        "Tarifa pagada",
        "Número de camarote",
        "Puerto de embarque (C, Q, S)"
    ]
}


df_diccionario = pd.DataFrame(data_dict)


print("Diccionario de datos del Titanic:")
display(df_diccionario)

Diccionario de datos del Titanic:

       Variable                               Descripción
0   PassengerId                       Identificador único
1      Survived         0 = No sobrevivió, 1 = Sobrevivió
2        Pclass  1 = 1ª Clase, 2 = 2ª Clase, 3 = 3ª Clase
3          Name                           Nombre y título
4           Sex                                    Género
5           Age                              Edad en años
6         SibSp           Nº de hermanos/cónyuges a bordo
7         Parch                Nº de padres/hijos a bordo
8        Ticket                         Número del ticket
9          Fare                             Tarifa pagada
10        Cabin                        Número de camarote
11     Embarked              Puerto de embarque (C, Q, S)

#### Punto 3
Comparacion de variables:

* Se puede ver que ambos dataframes, el de test y el de train, son bastanantes parecidos:
* En la edad el promedio es casi igual en ambos dataframes, igual en las tarifas
* Tenemos datos incompletos en ambos dataframes, por ejemplo en edad nos faltan datos en ambos
* En test no existe la columna survive

In [21]:
# Estadísticas del set de entrenamiento
print("Estadisticas descriptivas de TRAIN:")
display(train.describe())

print("\n--------------------------------------------------\n")

# Estadísticas del set de prueba
print("Estadisticas descriptivas de TEST:")
display(test.describe())

Estadisticas descriptivas de TRAIN:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

--------------------------------------------------

Estadisticas descriptivas de TEST:

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

#### Punto 4
SibSp: Es el número de hermanos o cónyuges

Parch: Es el numero de padres e hijos

¿Que opinamos de esta nueva variable?

Respuesta: Es mejor crear esta nueva variable ya que podemos simplificar las variables, asi podemos saber simplemente si viaja con alguien o viaja solo. Con una sola variable, al momento de predecir podria ser mejor tener menos variables

In [22]:
train['Familiares']= train['SibSp'] + train['Parch']
test['Familiares']= train['SibSp'] + train['Parch']
print(train[['SibSp', 'Parch', 'Familiares']].sample(10))

     SibSp  Parch  Familiares
685      1      2           3
308      1      0           1
543      1      0           1
537      0      0           0
252      0      0           0
849      1      0           1
27       3      2           5
482      0      0           0
29       0      0           0
283      0      0           0

#### punto 5.
Se dejaran sus valores NaN, no se debe borrar ya que permite identificar las filas de prueba y representa la variable que queremos predecir mas adelante

In [23]:
train['source'] = 'train'
test['source'] = 'test'

# pd.concat' las pega verticalmente
# ignore_index=True' rearma la numeración de las filas desde 0

datos_totales=pd.concat([train, test], ignore_index=True)
print(datos_totales)

      PassengerId  Survived  Pclass  \
0               1       0.0       3
1               2       1.0       1
2               3       1.0       3
3               4       1.0       1
4               5       0.0       3
...           ...       ...     ...
1304         1305       NaN       3
1305         1306       NaN       1
1306         1307       NaN       3
1307         1308       NaN       3
1308         1309       NaN       3

                                                   Name     Sex   Age  SibSp  \
0                               Braund, Mr. Owen Harris    male  22.0      1
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                                Heikkinen, Miss. Laina  female  26.0      0
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                              Allen, Mr. William Henry    male  35.0      0
...                                                 ...     ...   ...    ...
1304                                 Spector, Mr. Woolf    male   NaN      0
1305                       Oliva y Ocana, Dona. Fermina  female  39.0      0
1306                       Saether, Mr. Simon Sivertsen    male  38.5      0
1307                                Ware, Mr. Frederick    male   NaN      0
1308                           Peter, Master. Michael J    male   NaN      1

      Parch              Ticket      Fare Cabin Embarked  Familiares source
0         0           A/5 21171    7.2500   NaN        S           1  train
1         0            PC 17599   71.2833   C85        C           1  train
2         0    STON/O2. 3101282    7.9250   NaN        S           0  train
3         0              113803   53.1000  C123        S           1  train
4         0              373450    8.0500   NaN        S           0  train
...     ...                 ...       ...   ...      ...         ...    ...
1304      0           A.5. 3236    8.0500   NaN        S           0   test
1305      0            PC 17758  108.9000  C105        C           0   test
1306      0  SOTON/O.Q. 3101262    7.2500   NaN        S           0   test
1307      0              359309    8.0500   NaN        S           2   test
1308      1                2668   22.3583   NaN        C           2   test

[1309 rows x 14 columns]